# Welcome to Jekyll!
#
# About Theme
#
# Life’s messy, but growth is the point. A blog for strong, curious, masc women chasing goals and laughs along the way.
#
# Website: https://github.com/jeffreytse/jekyll-theme-yat
#
# You can do anything you want, including projects for your clients, as long
# as you mention an attribution back (credit links in footer or project).
# See the LICENCE file.
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you
# use 'bundle exec jekyll serve'. If you change this file, please restart
# the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Human Noodle
email: yeasyfitness@gmail.com
description: >-
  Life’s messy, but growth is the point. A blog for strong, curious, masc women chasing goals and laughs along the way.

# Copyright setting
copyright: "Unpublished Work (cleft) 2017-{currentYear} {author}"

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. https://example.com
favicon: "" # the favicon for your site

# YAT date format
yat:
  date_format: "%b %d, %Y"

# debug: false
# header_transparent: true
# content_width: "920px"

# Google analytics - GA4
# google_analytics: [Measurement ID]
# enableDNT: "false"

# sitemap: false
# lang: "en"  # default lang is en

# theme_color: snowwhite
# brand_color: orangered
# night_mode: "auto"

# code_badge:
#   enabled: "true"
#   color: "#fff"
#   background_color: "#ff4e00"
#   text_transform: "uppercase"

# header_pages:
#   - index.html
#   - archives.html
#   - categories.html
#   - tags.html
#   - about.md

defaults:
  home:
    heading: "Human Noodle"
    subheading: "The ongoing project"
    # banner: "Your image url"


# banner:
#   video: null
#   loop: true
#   volume: 0
#   start_at: 0
#   image: null
#   opacity: 1.0
#   background: "rgba(0, 0, 0, 0.8)"
#   height: "640px"
#   min_height: null
#   heading_style: null
#   subheading_style: null

# excerpt_size: 350
# paginate: 5

# disqus:
#   shortname: "Your Disqus username"

# gitment:
#   username: "Your GitHub username"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"

# utterances:
#   repo: "owner/repo"
#   issue_term: "title"
#   label: "utterances comment"
#   theme: "github-light"
#   follow_site_theme: true

# Build settings
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
