title: Human Noodle
email: yeasyfitness@gmail.com
description: >-
  Life’s messy, but growth is the point. A blog for strong, curious, masc women chasing goals and laughs along the way.

# Copyright setting
copyright: "Unpublished Work (cleft) 2017-{currentYear} {author}"

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. https://example.com
favicon: "" # the favicon for your site

# Yat date format
yat:
  date_format: "%b %d, %Y"

# debug: false
# header_transparent: true
# content_width: "920px"

# google_analytics: [Measurement ID]
# enableDNT: "false"

# sitemap: false
# lang: "en"  # default lang is en

# theme_color: snowwhite
# brand_color: orangered
# night_mode: "auto"

# code_badge:
#   enabled: "true"
#   color: "#fff"
#   background_color: "#ff4e00"
#   text_transform: "uppercase"

# header_pages:
#   - index.html
#   - archives.html
#   - categories.html
#   - tags.html
#   - about.md

# defaults:
#   home:
#     heading: "Human Noodle"
#     subheading: "Your awesome subheading"
#   banner: "Your image url"

# banner:
#   video: null
#   loop: true
#   volume: 0
#   start_at: 0
#   image: null
#   opacity: 1.0
#   background: "rgba(0, 0, 0, 0.8)"
#   height: "640px"
#   min_height: null
#   heading_style: null
#   subheading_style: null

# excerpt_size: 350
# paginate: 5

# disqus:
#   shortname: "Your Disqus username"

# gitment:
#   username: "Your GitHub username"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"

# utterances:
#   repo: "owner/repo"
#   issue_term: "title"
#   label: "utterances comment"
#   theme: "github-light"
#   follow_site_theme: true

markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
